/*
 * This file was automatically generated by tecsgen.
 * Move and rename like below before editing,
 *   gen/tPerson_templ.c => src/tPerson.c
 * to avoid to be overwritten by tecsgen.
 */
/* #[<PREAMBLE>]#
 * Don't edit the comments between #[<...>]# and #[</...>]#
 * These comment are used by tecsmerege when merging.
 *
 * #[</PREAMBLE>]# */

/* Put prototype declaration and/or variale definition here #_PAC_# */
#include "tPerson_tecsgen.h"

#ifndef E_OK
#define	E_OK	0		/* success */
#define	E_ID	(-18)	/* illegal ID */
#endif

/* entry port function #_TEPF_# */
/* #[<ENTRY_PORT>]# eGreet
 * entry port: eGreet
 * signature:  sGreet
 * context:    task
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eGreet_greetInKlingon
 * name:         eGreet_greetInKlingon
 * global_name:  tPerson_eGreet_greetInKlingon
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
ER
eGreet_greetInKlingon(CELLIDX idx)
{
	ER		ercd = E_OK;
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		return(E_ID);
	} /* end if VALID_IDX(idx) */

    syslog(LOG_NOTICE, "tPerson answered: 'nuqneH'");

	return(ercd);
}

/* #[<POSTAMBLE>]#
 *   Put non-entry functions below.
 * #[</POSTAMBLE>]#*/
